version: '3.3'

services:
  web:
    image: test_web
    build: .docker
    volumes:
      - ./:/var/www/html
      - ./.docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./.docker/cache:/cache
    ports:
      - '80:80'

  database:
    image: mariadb:latest
    volumes:
      - ./.docker/database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: test

  adminer:
    image: adminer:4.8.1
    ports:
      - '8081:8080'
    environment:
      ADMINER_DEFAULT_SERVER: database

  composer:
    image: composer:latest
    volumes:
      - ./:/app
      - ./.docker/cache:/cache
    working_dir: /app
    command: composer install --ignore-platform-reqs

  console:
    image: ghcr.io/webnazakazku/docker-php-build:8.0
    entrypoint: bash
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/cache:/cache
      - ./.docker/console/root:/root
